[tool.poetry]
name = "ex1"
version = "0.1.0"
description = "Loading Programs - Matrix Data Analysis"
authors = ["jabad-di <jabad-di@student.42.fr>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.0"
numpy = ">=1.25.0,<2.0.0"
matplotlib = "^3.7.2"
requests="^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"